services:
  db:
    image: MySQL/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIA_DATABASE: 350-Project
    ports:
      - "3306:3306"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "3307:80"
    depends_on:
      - db
