USE project_350;

CREATE TABLE `User`
(
  UserID SERIAL NOT NULL,
  UserFName VARCHAR(50) NOT NULL,
  UserLName VARCHAR(50) NOT NULL,
  Weight FLOAT,
  Height FLOAT,
  UserEmail VARCHAR(320) NOT NULL,
  UserPass VARCHAR(64) NOT NULL,
  Gender VARCHAR(6) NOT NULL,
  DoB DATE,
  PRIMARY KEY (UserID)
);

CREATE TABLE Workout
(
  Duration FLOAT,
  WorkoutType VARCHAR(100) NOT NULL,
  Reps FLOAT,
  WeightLifted FLOAT,
  WorkoutID SERIAL NOT NULL,
  PRIMARY KEY (WorkoutID)
);

CREATE TABLE Meal
(
  MealID SERIAL NOT NULL,
  DateEaten DATE NOT NULL,
  MealName VARCHAR(100) NOT NULL,
  UserID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (MealID),
  FOREIGN KEY (UserID) REFERENCES `User`(UserID)
);

CREATE TABLE Routine
(
  RoutineName VARCHAR(100) NOT NULL,
  DayOfWeek VARCHAR(12) NOT NULL,
  RoutineID SERIAL NOT NULL,
  UserID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (RoutineID),
  FOREIGN KEY (UserID) REFERENCES `User`(UserID)
);

CREATE TABLE Drink
(
  DrinkType VARCHAR(100) NOT NULL,
  Amount FLOAT NOT NULL,
  DrinkCalDensity FLOAT NOT NULL,
  DrinkID SERIAL NOT NULL,
  MealID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (DrinkID),
  FOREIGN KEY (MealID) REFERENCES Meal(MealID)
);

CREATE TABLE Ingredient
(
  IngredType VARCHAR(100) NOT NULL,
  IngredWeight FLOAT NOT NULL,
  FoodCalDensity FLOAT NOT NULL,
  IngredID SERIAL NOT NULL,
  MealID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (IngredID),
  FOREIGN KEY (MealID) REFERENCES Meal(MealID)
);

CREATE TABLE ComposedOf
(
  RoutineID BIGINT UNSIGNED NOT NULL,
  WorkoutID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (RoutineID, WorkoutID),
  FOREIGN KEY (RoutineID) REFERENCES Routine(RoutineID),
  FOREIGN KEY (WorkoutID) REFERENCES Workout(WorkoutID)
);
